// const players = [
//   {
//     name: "Ajay",
//     photo: "https://drive.google.com/u/1/open?usp=forms_web&id=1JTfBq-92SE15aIFI73S8objhxRfPeHcP",
//     phone: "7736198405",
//     position: "All-rounder",
//     club: "Stallions"
//   },
//   // Add all other players from your CSV data in the same format
//   // I'm showing just one for brevity, but you should include all
// ];

// const players =[
//     {
//         timestamp: "2025/05/14 12:29:27 PM GMT+5:30",
//         name: "Ajay",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1JTfBq-92SE15aIFI73S8objhxRfPeHcP",
//         phone_Number: "7736198405",
//         playing_Role: "All-rounder",
//         club: "Stallions",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=15FKzGZosHjAQRh3csy3Ge09Gk3WO3zJa",
//     },
//     {
//         timestamp: "2025/05/14 1:36:43 PM GMT+5:30",
//         name: "Anu",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1szbnR4JynYktXqoWHCvcV-zAFSgRbPl7",
//         phone_Number: "9745662513",
//         playing_Role: "All-rounder",
//         club: "Fighters ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1aGA6i02wXKz313gT1CPDIA89DcOI7O-U",
//     },
//     {
//         timestamp: "2025/05/14 1:37:56 PM GMT+5:30",
//         name: "Shaji",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1fR54JRSCYc6H0RFG-o7LMaSGEu0xbL7r",
//         phone_Number: "8086408908",
//         playing_Role: "Bowler",
//         club: "Fighters ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1WbMZll-FGfo2l2fmVljtYrfMFZANpZcm",
//     },
//     {
//         timestamp: "2025/05/14 1:57:14 PM GMT+5:30",
//         name: "SUBASH ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1UuInGdKbRGe6Pyg2ZPW2eISqHFU0_Czj",
//         phone_Number: "8089564748",
//         playing_Role: "All-rounder",
//         club: "NEW ROYAL",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1ofDYP6rgiOgrbGe1JAiB0c8GlAj1RJQf",
//     },
//     {
//         timestamp: "2025/05/14 5:50:08 PM GMT+5:30",
//         name: "Kevin",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1jEscA9xDeeZB9fLJ4qmgK1zK057xILFd",
//         phone_Number: "9895919578",
//         playing_Role: "All-rounder",
//         club: "Srs",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1IDpjFY6hJGb6xCaAZBptYjv66eerVz1q",
//         "\"\"": "9895919578"
//     },
//     {
//         timestamp: "2025/05/16 7:21:54 PM GMT+5:30",
//         name: "Sudheesh ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=156KCGLe2hcT6txmeILjibEoR69fRz477",
//         phone_Number: "7902828812",
//         playing_Role: "All-rounder",
//         club: "Chunkzzz",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1vfHU_6vDLe0RZtkexOqOfO0oe53eVec7",
//         "\"\"": "7902828812"
//     },
//     {
//         timestamp: "2025/05/17 12:34:51 PM GMT+5:30",
//         name: "Jaya Prakash",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1FK-4aCORqU2oM3ryHWsAGz2J4hR1aPfZ",
//         phone_Number: "9633051783",
//         playing_Role: "All-rounder",
//         club: "Scorpion cc",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1VZDQq5_-1AmY95ox6_RaYD7hfxgZP6SL",
//         "\"\"": "513794039540"
//     },
//     {
//         timestamp: "2025/05/17 4:11:17 PM GMT+5:30",
//         name: "Soorya.p",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1mCCKa7Yyc-MYyPuqaQSGkDkdNMZLNdBf",
//         phone_Number: "9037045641",
//         playing_Role: "All-rounder",
//         club: "New royals",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1hSLIuRnDpENa6r5hLA-IdVxlGO7bv0lO",
//         "\"\"": "9037045641"
//     },
//     {
//         timestamp: "2025/05/17 6:46:23 PM GMT+5:30",
//         name: "Madhu M",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=16nfrIko9ImljgBxN4-mq_dcCuof92FTs",
//         phone_Number: "9074054009",
//         playing_Role: "All-rounder",
//         club: "New Royals",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1ktftVyHcblN2K9obmSjSS5ZfcGYYOxur",
//         "\"\"": "513725284960"
//     },
//     {
//         timestamp: "2025/05/17 7:37:50 PM GMT+5:30",
//         name: "Azar",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1eYjO3UTVFTZL6iPQdiCB6EMwlkBmLtEP",
//         phone_Number: "8089818127",
//         playing_Role: "All-rounder",
//         club: "Bcc canalpirivu",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1NMG8YIUoXMwsKb-7Z4mvjkIn_BR80BTN",
//         "\"\"": "12345678"
//     },
//     {
//         timestamp: "2025/05/18 2:22:46 PM GMT+5:30",
//         name: "Vishnu",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1OexwyyoYUOTmMnG7fRhnd7TLqkEimjLj",
//         phone_Number: "6282694916",
//         playing_Role: "All-rounder",
//         club: "Vattappara",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1eCdZAePyXLkjVZniavD0-qSd6CyQeUJk",
//         "\"\"": "1234568"
//     },
//     {
//         timestamp: "2025/05/18 6:36:59 PM GMT+5:30",
//         name: "Ranjith",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1_BiP10CuId4Vjw-lIXd50w3nzr4uONOP",
//         phone_Number: "7994822612",
//         playing_Role: "All-rounder",
//         club: "Scorpions",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1jFfcGVn3eqi2M3OTSe_mnYoqWa-L5r4A",
//         "\"\"": "513869293027"
//     },
//     {
//         timestamp: "2025/05/18 7:50:16 PM GMT+5:30",
//         name: "Daison ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1m0vnoMv5a5h-4vgcwZ4mj_mjfqnQPJjv",
//         phone_Number: "9544633806",
//         playing_Role: "All-rounder",
//         club: "Pkd boys ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Om9Acw_T5io_QhF0BFJCdQ2Vms_RTKoR",
//     },
//     {
//         timestamp: "2025/05/19 12:40:54 PM GMT+5:30",
//         name: "Aneesh",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1MruA63sjeC7N971GaM-xH3KaxbxzIevw",
//         phone_Number: "7907786334",
//         playing_Role: "All-rounder",
//         club: "Nallur rising star",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Rx5FgOmGlAyjyPH6BAw43CNejP5f_BWE",
//     },
//     {
//         timestamp: "2025/05/19 5:50:13 PM GMT+5:30",
//         name: "Sadhik kozhinjampara ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1H01aGMt9t5Aw6E8lY06-xp0QK-J6xN4M",
//         phone_Number: "9496921828",
//         playing_Role: "All-rounder",
//         club: "Phoenix kozhinjampara",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1nBLFybTdyzRTcXb4seVnbfY7I3cxm_yy",
//     },
//     {
//         timestamp: "2025/05/19 8:04:26 PM GMT+5:30",
//         name: "Arun ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=11hYhG37Qqh31CZM-J7vitHaAjERjs21C",
//         phone_Number: "7909236684",
//         playing_Role: "All-rounder",
//         club: "Stallions ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1RQ18ZNWNlfcTkG324huxLj8UU1p9RTQC",
//     },
//     {
//         timestamp: "2025/05/19 9:24:17 PM GMT+5:30",
//         name: "Thamil",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1IhcaX_FF2sO8Yrhm_Rrxh2Jz-4vm89ud",
//         phone_Number: "9995655454",
//         playing_Role: "All-rounder",
//         club: "Blasters cc",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=161_aRB5vkpuXVkXodyIrsSYOl32s56Ox",
//     },
//     {
//         timestamp: "2025/05/19 9:26:48 PM GMT+5:30",
//         name: "Ruban",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=14pVb9uNm1v39BY16frj2Qc3MuXILHSc4",
//         phone_Number: "7510774769",
//         playing_Role: "All-rounder",
//         club: "Ekr cricketers ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Lb-TPOXwLaJ22nO5TQTK-utibGNrSJJ1",
//     },
//     {
//         timestamp: "2025/05/19 9:28:07 PM GMT+5:30",
//         name: "Ismail ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1qp9p8eTTt5ZkikzdqJh7qjwhd9It3oWT",
//         phone_Number: "9074312043",
//         playing_Role: "All-rounder",
//         club: "Scorpions ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1bhFjjgwRyf1J7y15zh8N8H_RyHjcWU9k",
//     },
//     {
//         timestamp: "2025/05/19 9:32:46 PM GMT+5:30",
//         name: "Francis ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=17Di-Ial4tZOcXSVNVNtMqqsFhhJyK4sV",
//         phone_Number: "9946209762",
//         playing_Role: "All-rounder",
//         club: "Pkd boys",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1O76el1KdPJDfoXPixI4uVm4EWMgBJt-U",
//     },
//     {
//         timestamp: "2025/05/20 6:35:28 AM GMT+5:30",
//         name: "Manikandan.d",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1hF4Fz-gF1mCdAgX2ZylO_ho5NbMH1NQh",
//         phone_Number: "9074015886",
//         playing_Role: "All-rounder",
//         club: "FIGHTERS",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1rIgzalhVYPm-ojNh73x6V8DnBqr_DgSQ",
//     },
//     {
//         timestamp: "2025/05/20 6:56:53 AM GMT+5:30",
//         name: "Mathew ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1yZF10INXt_to1B8_0zQpxz9UtXwnQdDb",
//         phone_Number: "6238172824",
//         playing_Role: "All-rounder",
//         club: "Stephen cc",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1JEeryC0MsISZDxfYRrOo8Wj1iqUQDZhZ",
//     },
//     {
//         timestamp: "2025/05/20 9:04:07 AM GMT+5:30",
//         name: "Akhil ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1GWDDV_1y24xWGd-gGY7j57sQb4PZejSr",
//         phone_Number: "6238541961",
//         playing_Role: "All-rounder",
//         club: "Dracarys ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1RHtZPPBeFGnG-86oh1jGwFj-S98qviwP",
//     },
//     {
//         timestamp: "2025/05/20 9:07:21 AM GMT+5:30",
//         name: "Pradeep",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1cFAhSZno3RfFGeM0UMnpBZEqWOk5XwAn",
//         phone_Number: "9809332833",
//         playing_Role: "Batsman",
//         club: "Fightrs",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=120qOhbri2MFSSHcefBQFyAHfJFrR419o",
//     },
//     {
//         timestamp: "2025/05/20 12:54:22 PM GMT+5:30",
//         name: "JERIN ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1F2MsHErxbT9WpXnTYJE_EFhq96NsHKao",
//         phone_Number: "7012225381 ",
//         playing_Role: "All-rounder",
//         club: "Stallion ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1kJmvM6-eMM0AUyfU3Ab6uI7an5djYt3H",
//     },
//     {
//         timestamp: "2025/05/20 1:33:17 PM GMT+5:30",
//         name: "Daniel",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1wKTjBX4rYaX3UE8sT5XExmCDM41nXbXQ",
//         phone_Number: "7025242361",
//         playing_Role: "Wicket Keeper",
//         club: "Stallions ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1ksX2bZ2hIDNyEnkQHHRTMli-qjV21C9j",
//     },
//     {
//         timestamp: "2025/05/20 1:46:54 PM GMT+5:30",
//         name: "Vishnu",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1qKCIK2ZmdlyXVP63M89W34xlWhN8vyu8",
//         phone_Number: "7306042080",
//         playing_Role: "All-rounder",
//         club: "Phoenix",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1uJ5c9-68rE4hgeRelxtVHL6nfqHQKz-H",
//     },
//     {
//         timestamp: "2025/05/20 2:19:37 PM GMT+5:30",
//         name: "Paul ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1jVxYqotbOijKqM-Y0eBabEnsZbFXNzum",
//         phone_Number: "8129036415",
//         playing_Role: "All-rounder",
//         club: "Speed boys ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1TxUTb007yH6lewM4zFdtXWR__bByV_A3",
//     },
//     {
//         timestamp: "2025/05/20 3:16:59 PM GMT+5:30",
//         name: "Edit",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1fboY5_723hC7sQMqyz6uGurYqqCG4xFG",
//         phone_Number: "6238161701",
//         playing_Role: "All-rounder",
//         club: "Jokerz",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1iv-n5b0Jy3LnCiRPzEhkKHtwpfBoPQvV",
//     },
//     {
//         timestamp: "2025/05/20 3:18:43 PM GMT+5:30",
//         name: "Edit",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1BEMmdf2PAYgPe6PNGvfr-yFeNXyFYGLR",
//         phone_Number: "6238161701",
//         playing_Role: "All-rounder",
//         club: "Jokerz",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1gH-COFZX_W-0YCGuzVu4gA_zGntFLpDY",
//     },
//     {
//         timestamp: "2025/05/20 3:37:55 PM GMT+5:30",
//         name: "Mani jockerz ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1viZry3UMaGwSTiMtDVk9MLRqRQsbaypk",
//         phone_Number: "7025839343 ",
//         playing_Role: "All-rounder",
//         club: "Jockerz ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1wbOAljxJQpbDF_QhePRwM7E7RYj1dlcR",
//     },
//     {
//         timestamp: "2025/05/20 7:11:36 PM GMT+5:30",
//         name: "Charly",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1pNBQjAX2tCNf03H4nRSYbB5kvoMQSnuW",
//         phone_Number: "7559937279",
//         playing_Role: "Batsman",
//         club: "Ekr cricketers",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1EOi5mcbxl9HgRnLWCMC5QOIqFIHdoCTq",
//     },
//     {
//         timestamp: "2025/05/20 7:51:54 PM GMT+5:30",
//         name: "Kiran ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1q5l53Q6t9YjEN8If1gWtDicvvCIMQobA",
//         phone_Number: "9946250266",
//         playing_Role: "Batsman",
//         club: "Stallions",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1eZqc6MoSpvD6OoSmU4XSoIZ6Cy3m6Dkw",
//     },
//     {
//         timestamp: "2025/05/20 8:15:29 PM GMT+5:30",
//         name: "Manu",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1olMMt20ptKkCxibwTMPbxebUHcKu9Snd",
//         phone_Number: "9072118650",
//         playing_Role: "Bowler",
//         club: "Jokerz",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1KMtMGoSleQRmbhXMr2A3PvC_H9Uox0jM",
//     },
//     {
//         timestamp: "2025/05/20 9:11:53 PM GMT+5:30",
//         name: "Manju",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1SMpxlvP8epmLfR5Lnndv1zvkrcDu_fpy",
//         phone_Number: "7356948017",
//         playing_Role: "All-rounder",
//         club: "Ekr Cricketers",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1BbyokykSdMdwVDhOgEwXsJ18Oys-hp5V",
//     },
//     {
//         timestamp: "2025/05/20 9:13:51 PM GMT+5:30",
//         name: "Praveen",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1-nGJwIf7FkbKTxSm3kwSLQjsdmWqQnbu",
//         phone_Number: "9526650092",
//         playing_Role: "Batsman",
//         club: "Erumaikkaranoor ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1GRBRJD-uPkEIs2Lvkqim3DAhlHUgdcgk",
//     },
//     {
//         timestamp: "2025/05/21 9:40:26 AM GMT+5:30",
//         name: "Salman farish",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1bDXS7AwcDoVuqG9XeS6Z6fO2nR9NjgUb",
//         phone_Number: "9074215058",
//         playing_Role: "All-rounder",
//         club: "Nallur rising star's ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1-CBZ_le8ikzyeIoCZvJP5A5Q-CNUVOE1",
//     },
//     {
//         timestamp: "2025/05/21 9:43:11 AM GMT+5:30",
//         name: "Salman farish ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1h4csArCu70swysZq_V3UnZi9yA4OWhI8",
//         phone_Number: "9074215058",
//         playing_Role: "All-rounder",
//         club: "Nallur rising star's ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1U_R7cjpzt6RS8T1QY3Pby7t3Np4eom-Z",
//     },
//     {
//         timestamp: "2025/05/21 9:49:54 AM GMT+5:30",
//         name: "ANDROS",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1ZxLXByvdiYVt4fxhqKs9nh0GyPL9Hn3I",
//         phone_Number: "9497312928",
//         playing_Role: "All-rounder",
//         club: "Nallur rising star",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1EPc2B--IqQ4v4ZvS0EKTdNduFOywyQlT",
//     },
//     {
//         timestamp: "2025/05/21 7:43:52 PM GMT+5:30",
//         name: "Akshay",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1g8cYUrbm8P0OZpsoiKDV8dVMw-oh6cXJ",
//         phone_Number: "8891163595",
//         playing_Role: "All-rounder",
//         club: "Bsa",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1DB38g4SzGN9IIZFZ_z9i-TZjoPaY1Uan",
//     },
//     {
//         timestamp: "2025/05/21 7:51:58 PM GMT+5:30",
//         name: "Skuttan",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1x1j5AmS6BzvhEmnQ-d7AyMfVFM7l_nrh",
//         phone_Number: "7560969865",
//         playing_Role: "All-rounder",
//         club: "Bsa",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1GIVmM92j4vTSh29KIQoN1WnCxbMzhZut",
//     },
//     {
//         timestamp: "2025/05/21 8:04:18 PM GMT+5:30",
//         name: "Sruthish s",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1wPuqNnLOp1H1U9D9PV7VSXEJY99fuyfB",
//         phone_Number: "8590370524",
//         playing_Role: "All-rounder",
//         club: "Bsa",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1U1XIdk3pfg7DmSpCSLKPIGBKeZkonx43",
//     },
//     {
//         timestamp: "2025/05/21 10:16:27 PM GMT+5:30",
//         name: "Rajesh",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1_-89xLBzbcCvGaC6eKHeKQ-IRfXgUsTZ",
//         phone_Number: "9809690208",
//         playing_Role: "All-rounder",
//         club: "KL BROTHERS",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1FeMY27_IEe8c6mYzN0IZPPYTFvSFB2pk",
//     },
//     {
//         timestamp: "2025/05/22 11:15:41 AM GMT+5:30",
//         name: "Abbas ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1yMXfqt9A8XI06eESJPKc3Dai1w1Gkaui",
//         phone_Number: "9995634599",
//         playing_Role: "All-rounder",
//         club: "Kl brother ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1p99enwGkFUiYNUaIPX67TDAlnDTaTTn_",
//     },
//     {
//         timestamp: "2025/05/22 1:11:42 PM GMT+5:30",
//         name: "Kalai ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1-5dKHiO20BdYtm8ZYjM6nS34Z1GtGmtd",
//         phone_Number: "9562828301",
//         playing_Role: "All-rounder",
//         club: "Phoenix Kozhinjampara ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1p0EUMalFN5HtWkMdAxrVywA4MK4zh5Hz",
//     },
//     {
//         timestamp: "2025/05/22 1:17:08 PM GMT+5:30",
//         name: "Agilesh ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1LzGbjKlrxXUY54LDxhwGR-bgtFMqYP5J",
//         phone_Number: "9809200670",
//         playing_Role: "All-rounder",
//         club: "Phoenix ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1aBCKGCbxB4Cg8aC-vSQ52Tj8b8CXNP0L",
//     },
//     {
//         timestamp: "2025/05/22 1:20:40 PM GMT+5:30",
//         name: "Anees uv",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1ZxDvabp-EtpqGrlCaD3Pc-OKvcDv5UGf",
//         phone_Number: "8137007221",
//         playing_Role: "All-rounder",
//         club: "Walayar Champions club ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1vx7j_FXXgGv5v91r2iGfsB4GoejSHMCd",
//     },
//     {
//         timestamp: "2025/05/22 1:24:05 PM GMT+5:30",
//         name: "Bibinraj",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1qo2lzKpy87ez-w9JCRDBrWx6TU8wQ5Jv",
//         phone_Number: "9946497133",
//         playing_Role: "All-rounder",
//         club: "Kongampara ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1-fFJ7-G83s851qgAeCOqcB6VIavWUtll",
//     },
//     {
//         timestamp: "2025/05/22 7:06:01 PM GMT+5:30",
//         name: "Asharaf ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1e9lewI8sOcLaDYv6RBhCmADC0qLgdkVC",
//         phone_Number: "7708609308",
//         playing_Role: "All-rounder",
//         club: "Pheonix ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=14Of0ra1YbJ8ze4V9yQKW3dEoPfo-gKZe",
//     },
//     {
//         timestamp: "2025/05/22 7:19:20 PM GMT+5:30",
//         name: "Jose",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1NOTQ_ytadgSWuBZU_sR_0UV28EXRZNwr",
//         phone_Number: "9656289774",
//         playing_Role: "All-rounder",
//         club: "Klcc",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1zlJqnBk4NPOEwVIZQtmY2nX-eECPkh63",
//     },
//     {
//         timestamp: "2025/05/22 7:20:41 PM GMT+5:30",
//         name: "Albi",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1OPCIp_ZFQ1FztmbUcAlVcRYtwLxn67le",
//         phone_Number: "7907877289",
//         playing_Role: "All-rounder",
//         club: "Scorpions ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Dr8G8auDd76uyU4PE50Y96e6D71hBOxf",
//     },
//     {
//         timestamp: "2025/05/22 7:21:47 PM GMT+5:30",
//         name: "Kevin ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=13YZCTNNBMEk3NPyAsaLL6s-SEaWelnSx",
//         phone_Number: "9207901704",
//         playing_Role: "All-rounder",
//         club: "Stallions lo",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1h9YHUhuEREUFknDgZG0dmWSu-OegMovz",
//     },
//     {
//         timestamp: "2025/05/22 7:24:13 PM GMT+5:30",
//         name: "Jerom",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1ONJn6OO-1dxi5cyKKdyowVWkMbJUG6K8",
//         phone_Number: "9539680590",
//         playing_Role: "All-rounder",
//         club: "Blasters cc ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1zrumKzFtvM0E7zZqeUQrwD_LHmKaJk5z",
//     },
//     {
//         timestamp: "2025/05/22 8:15:23 PM GMT+5:30",
//         name: "Staney",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1RpHJQONUkBJKgi2PH2RLNT_id0v577it",
//         phone_Number: "9074172452",
//         playing_Role: "All-rounder",
//         club: "Pkd boys",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1N0dvvbm7cLeqiJh7nCkej8nTE4f_7DoV",
//     },
//     {
//         timestamp: "2025/05/22 8:17:24 PM GMT+5:30",
//         name: "KATHIR",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1bBdvNHYRmcgw1JaKVWSlpnqbH9NBEkoe",
//         phone_Number: "8075802086",
//         playing_Role: "All-rounder",
//         club: "KL.BROTHERS",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1rGpr4NTeBaNL9cpKhCTbZXaWPAPb5L3O",
//     },
//     {
//         timestamp: "2025/05/22 10:50:35 PM GMT+5:30",
//         name: "Aji",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1PHbDgsj6Wkfgzw_ywXN4gG7NkBV5JWic",
//         phone_Number: "7012816557",
//         playing_Role: "All-rounder",
//         club: "New Royals vattappara",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1C9z36gtZg5XEu_5cp0HUJtNl59TgEaov",
//     },
//     {
//         timestamp: "2025/05/22 10:55:19 PM GMT+5:30",
//         name: "Adhi",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=168QA75Trrc75X7sbcpAu4O4iRUAAcxMa",
//         phone_Number: "7736055641",
//         playing_Role: "All-rounder",
//         club: "New Royals vattappara",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=18Bs9QYKolVTci129voO86_UGILisWpfl",
//     },
//     {
//         timestamp: "2025/05/22 10:57:25 PM GMT+5:30",
//         name: "Adhi",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1MZ5dI8Z34sdeIwMpVib5i7OKh4jRKqBP",
//         phone_Number: "7736055641",
//         playing_Role: "All-rounder",
//         club: "New Royals vattappara",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=16CUHOhR-I1mDOa9AexNN_7ifVuLrur7v",
//     },
//     {
//         timestamp: "2025/05/23 8:30:46 AM GMT+5:30",
//         name: "STANLY LEO V",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1OpN_VqtCuRqOYmhEjJVdqg8P9oU1yTZ_",
//         phone_Number: "8082202877",
//         playing_Role: "All-rounder",
//         club: "Stallions ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Jp9tFkcxDlcCy1bWkZ70fIAIMWCuTLUg",
//     },
//     {
//         timestamp: "2025/05/23 8:41:59 AM GMT+5:30",
//         name: "Ebin",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=14G6oAdO8WIOhsjRr1lcKgcAuH9jpxRS5",
//         phone_Number: "7907978734",
//         playing_Role: "Batsman",
//         club: "Pkd boys",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1nTjEht3pD9wvtdE2-nzMUIFSwme78bHK",
//     },
//     {
//         timestamp: "2025/05/23 8:53:13 AM GMT+5:30",
//         name: "Nithin ",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1Z3TltX6k3_0aqMClcvB9nqP9QZNbU5j5",
//         phone_Number: "9995391974",
//         playing_Role: "All-rounder",
//         club: "PKD BOYS",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Si8IicifIaf1IiGwlkwg55qahzxvQcpk",
//     },
//     {
//         timestamp: "2025/05/23 9:11:47 AM GMT+5:30",
//         name: "Reni",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1UaYOe3jLsG_nz-_aTlYrgZHaYbUk4WHT",
//         phone_Number: "8848936996",
//         playing_Role: "Batsman",
//         club: "Unbeatable titans",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Mr6YOlEQkYauSU6LkLoMQS808mKMKWH6",
//     },
//     {
//         timestamp: "2025/05/23 11:30:07 AM GMT+5:30",
//         name: "Midhush",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1ZD31jtsDL5YycYicejLrV5HUgESUkqqD",
//         phone_Number: "9777104642",
//         playing_Role: "Bowler",
//         club: "Devilzz",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1tc5BtuD9uGavsLWf3Vaem3OgHxQH0a9N",
//     },
//     {
//         timestamp: "2025/05/23 1:19:33 PM GMT+5:30",
//         name: "Naveen NS",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=19l35wI4qzZyy727Lyb84Rlg_lrAv3081",
//         phone_Number: "8848209277",
//         playing_Role: "Batsman",
//         club: "Phoenix",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=16ZWlKxxNdd96G_PIRI6Y0C_wbWndlKrh",
//     },
//     {
//         timestamp: "2025/05/23 6:22:18 PM GMT+5:30",
//         name: "Dhanee",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1nBMY5X6ONCbgOHcqg3BumPLaZ_HsmHdH",
//         phone_Number: "+918590188293",
//         playing_Role: "All-rounder",
//         club: "Fighters kozhinjamPara ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1v6bzeiBFlIYW_dMPGzK3f68fdlSKWgb4",
//     },
//     {
//         timestamp: "2025/05/23 6:44:42 PM GMT+5:30",
//         name: "Jikson A",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1gxQJi1bYYmwTnEa-IK7tTHUVDvrDZtmt",
//         phone_Number: "7012295719",
//         playing_Role: "All-rounder",
//         club: "Skyhawks ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1G8q_h-6P8cWq5SF741Sg5_LtCTRIvEkv",
//     },
//     {
//         timestamp: "2025/05/23 8:41:19 PM GMT+5:30",
//         name: "Akash",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1d5hwi9cmxqs3PgmOml5wyjh1Hrc-iIev",
//         phone_Number: "8078908124",
//         playing_Role: "All-rounder",
//         club: "Phoenix ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=11jVvHKUpYYiHvN-U1NNZprVrGCoKz3x5",
//     },
//     {
//         timestamp: "2025/05/23 8:49:31 PM GMT+5:30",
//         name: "Rassu",
//         photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1hGhhSfTxLcVyfbjZpBwr__KDR1GQkzcP",
//         phone_Number: "8547611432",
//         playing_Role: "Bowler",
//         club: "Phoenix ",
//         upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1MBzTVxaQyejfZ4veGfJZ6pxbz2GOktHh",
//     }
// ]

const players = [
    {
        timeStamp: "2025/05/14 12:29:27 PM GMT+5:30",
        name: "Ajay",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1JTfBq-92SE15aIFI73S8objhxRfPeHcP",
        phone_Number: "7736198405",
        playing_Role: "All-rounder",
        club: "Stallions",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=15FKzGZosHjAQRh3csy3Ge09Gk3WO3zJa",
    },
    {
        timeStamp: "2025/05/14 1:36:43 PM GMT+5:30",
        name: "Anu",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1szbnR4JynYktXqoWHCvcV-zAFSgRbPl7",
        phone_Number: "9745662513",
        playing_Role: "All-rounder",
        club: "Fighters ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1aGA6i02wXKz313gT1CPDIA89DcOI7O-U",
    },
    {
        timeStamp: "2025/05/14 1:37:56 PM GMT+5:30",
        name: "Shaji",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1fR54JRSCYc6H0RFG-o7LMaSGEu0xbL7r",
        phone_Number: "8086408908",
        playing_Role: "Bowler",
        club: "Fighters ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1WbMZll-FGfo2l2fmVljtYrfMFZANpZcm",
    },
    {
        timeStamp: "2025/05/14 1:57:14 PM GMT+5:30",
        name: "SUBASH ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1UuInGdKbRGe6Pyg2ZPW2eISqHFU0_Czj",
        phone_Number: "8089564748",
        playing_Role: "All-rounder",
        club: "NEW ROYAL",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1ofDYP6rgiOgrbGe1JAiB0c8GlAj1RJQf",
    },
    {
        timeStamp: "2025/05/14 5:50:08 PM GMT+5:30",
        name: "Kevin",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1jEscA9xDeeZB9fLJ4qmgK1zK057xILFd",
        phone_Number: "9895919578",
        playing_Role: "All-rounder",
        club: "Srs",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1IDpjFY6hJGb6xCaAZBptYjv66eerVz1q",
        "\"\"": "9895919578"
    },
    {
        timeStamp: "2025/05/16 7:21:54 PM GMT+5:30",
        name: "Sudheesh ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=156KCGLe2hcT6txmeILjibEoR69fRz477",
        phone_Number: "7902828812",
        playing_Role: "All-rounder",
        club: "Chunkzzz",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1vfHU_6vDLe0RZtkexOqOfO0oe53eVec7",
        "\"\"": "7902828812"
    },
    {
        timeStamp: "2025/05/17 12:34:51 PM GMT+5:30",
        name: "Jaya Prakash",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1FK-4aCORqU2oM3ryHWsAGz2J4hR1aPfZ",
        phone_Number: "9633051783",
        playing_Role: "All-rounder",
        club: "Scorpion cc",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1VZDQq5_-1AmY95ox6_RaYD7hfxgZP6SL",
        "\"\"": "513794039540"
    },
    {
        timeStamp: "2025/05/17 4:11:17 PM GMT+5:30",
        name: "Soorya.p",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1mCCKa7Yyc-MYyPuqaQSGkDkdNMZLNdBf",
        phone_Number: "9037045641",
        playing_Role: "All-rounder",
        club: "New royals",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1hSLIuRnDpENa6r5hLA-IdVxlGO7bv0lO",
        "\"\"": "9037045641"
    },
    {
        timeStamp: "2025/05/17 6:46:23 PM GMT+5:30",
        name: "Madhu M",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=16nfrIko9ImljgBxN4-mq_dcCuof92FTs",
        phone_Number: "9074054009",
        playing_Role: "All-rounder",
        club: "New Royals",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1ktftVyHcblN2K9obmSjSS5ZfcGYYOxur",
        "\"\"": "513725284960"
    },
    {
        timeStamp: "2025/05/17 7:37:50 PM GMT+5:30",
        name: "Azar",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1eYjO3UTVFTZL6iPQdiCB6EMwlkBmLtEP",
        phone_Number: "8089818127",
        playing_Role: "All-rounder",
        club: "Bcc canalpirivu",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1NMG8YIUoXMwsKb-7Z4mvjkIn_BR80BTN",
        "\"\"": "12345678"
    },
    {
        timeStamp: "2025/05/18 2:22:46 PM GMT+5:30",
        name: "Vishnu",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1OexwyyoYUOTmMnG7fRhnd7TLqkEimjLj",
        phone_Number: "6282694916",
        playing_Role: "All-rounder",
        club: "Vattappara",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1eCdZAePyXLkjVZniavD0-qSd6CyQeUJk",
        "\"\"": "1234568"
    },
    {
        timeStamp: "2025/05/18 6:36:59 PM GMT+5:30",
        name: "Ranjith",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1_BiP10CuId4Vjw-lIXd50w3nzr4uONOP",
        phone_Number: "7994822612",
        playing_Role: "All-rounder",
        club: "Scorpions",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1jFfcGVn3eqi2M3OTSe_mnYoqWa-L5r4A",
        "\"\"": "513869293027"
    },
    {
        timeStamp: "2025/05/18 7:50:16 PM GMT+5:30",
        name: "Daison ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1m0vnoMv5a5h-4vgcwZ4mj_mjfqnQPJjv",
        phone_Number: "9544633806",
        playing_Role: "All-rounder",
        club: "Pkd boys ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Om9Acw_T5io_QhF0BFJCdQ2Vms_RTKoR",
    },
    {
        timeStamp: "2025/05/19 12:40:54 PM GMT+5:30",
        name: "Aneesh",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1MruA63sjeC7N971GaM-xH3KaxbxzIevw",
        phone_Number: "7907786334",
        playing_Role: "All-rounder",
        club: "Nallur rising star",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Rx5FgOmGlAyjyPH6BAw43CNejP5f_BWE",
    },
    {
        timeStamp: "2025/05/19 5:50:13 PM GMT+5:30",
        name: "Sadhik kozhinjampara ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1H01aGMt9t5Aw6E8lY06-xp0QK-J6xN4M",
        phone_Number: "9496921828",
        playing_Role: "All-rounder",
        club: "Phoenix kozhinjampara",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1nBLFybTdyzRTcXb4seVnbfY7I3cxm_yy",
    },
    {
        timeStamp: "2025/05/19 8:04:26 PM GMT+5:30",
        name: "Arun ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=11hYhG37Qqh31CZM-J7vitHaAjERjs21C",
        phone_Number: "7909236684",
        playing_Role: "All-rounder",
        club: "Stallions ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1RQ18ZNWNlfcTkG324huxLj8UU1p9RTQC",
    },
    {
        timeStamp: "2025/05/19 9:24:17 PM GMT+5:30",
        name: "Thamil",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1IhcaX_FF2sO8Yrhm_Rrxh2Jz-4vm89ud",
        phone_Number: "9995655454",
        playing_Role: "All-rounder",
        club: "Blasters cc",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=161_aRB5vkpuXVkXodyIrsSYOl32s56Ox",
    },
    {
        timeStamp: "2025/05/19 9:26:48 PM GMT+5:30",
        name: "Ruban",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=14pVb9uNm1v39BY16frj2Qc3MuXILHSc4",
        phone_Number: "7510774769",
        playing_Role: "All-rounder",
        club: "Ekr cricketers ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Lb-TPOXwLaJ22nO5TQTK-utibGNrSJJ1",
    },
    {
        timeStamp: "2025/05/19 9:28:07 PM GMT+5:30",
        name: "Ismail ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1qp9p8eTTt5ZkikzdqJh7qjwhd9It3oWT",
        phone_Number: "9074312043",
        playing_Role: "All-rounder",
        club: "Scorpions ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1bhFjjgwRyf1J7y15zh8N8H_RyHjcWU9k",
    },
    {
        timeStamp: "2025/05/19 9:32:46 PM GMT+5:30",
        name: "Francis ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=17Di-Ial4tZOcXSVNVNtMqqsFhhJyK4sV",
        phone_Number: "9946209762",
        playing_Role: "All-rounder",
        club: "Pkd boys",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1O76el1KdPJDfoXPixI4uVm4EWMgBJt-U",
    },
    {
        timeStamp: "2025/05/20 6:35:28 AM GMT+5:30",
        name: "Manikandan.d",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1hF4Fz-gF1mCdAgX2ZylO_ho5NbMH1NQh",
        phone_Number: "9074015886",
        playing_Role: "All-rounder",
        club: "FIGHTERS",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1rIgzalhVYPm-ojNh73x6V8DnBqr_DgSQ",
    },
    {
        timeStamp: "2025/05/20 6:56:53 AM GMT+5:30",
        name: "Mathew ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1yZF10INXt_to1B8_0zQpxz9UtXwnQdDb",
        phone_Number: "6238172824",
        playing_Role: "All-rounder",
        club: "Stephen cc",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1JEeryC0MsISZDxfYRrOo8Wj1iqUQDZhZ",
    },
    {
        timeStamp: "2025/05/20 9:04:07 AM GMT+5:30",
        name: "Akhil ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1GWDDV_1y24xWGd-gGY7j57sQb4PZejSr",
        phone_Number: "6238541961",
        playing_Role: "All-rounder",
        club: "Dracarys ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1RHtZPPBeFGnG-86oh1jGwFj-S98qviwP",
    },
    {
        timeStamp: "2025/05/20 9:07:21 AM GMT+5:30",
        name: "Pradeep",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1cFAhSZno3RfFGeM0UMnpBZEqWOk5XwAn",
        phone_Number: "9809332833",
        playing_Role: "Batsman",
        club: "Fightrs",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=120qOhbri2MFSSHcefBQFyAHfJFrR419o",
    },
    {
        timeStamp: "2025/05/20 12:54:22 PM GMT+5:30",
        name: "JERIN ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1F2MsHErxbT9WpXnTYJE_EFhq96NsHKao",
        phone_Number: "7012225381 ",
        playing_Role: "All-rounder",
        club: "Stallion ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1kJmvM6-eMM0AUyfU3Ab6uI7an5djYt3H",
    },
    {
        timeStamp: "2025/05/20 1:33:17 PM GMT+5:30",
        name: "Daniel",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1wKTjBX4rYaX3UE8sT5XExmCDM41nXbXQ",
        phone_Number: "7025242361",
        playing_Role: "Wicket Keeper",
        club: "Stallions ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1ksX2bZ2hIDNyEnkQHHRTMli-qjV21C9j",
    },
    {
        timeStamp: "2025/05/20 1:46:54 PM GMT+5:30",
        name: "Vishnu",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1qKCIK2ZmdlyXVP63M89W34xlWhN8vyu8",
        phone_Number: "7306042080",
        playing_Role: "All-rounder",
        club: "Phoenix",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1uJ5c9-68rE4hgeRelxtVHL6nfqHQKz-H",
    },
    {
        timeStamp: "2025/05/20 2:19:37 PM GMT+5:30",
        name: "Paul ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1jVxYqotbOijKqM-Y0eBabEnsZbFXNzum",
        phone_Number: "8129036415",
        playing_Role: "All-rounder",
        club: "Speed boys ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1TxUTb007yH6lewM4zFdtXWR__bByV_A3",
    },
    {
        timeStamp: "2025/05/20 3:16:59 PM GMT+5:30",
        name: "Edit",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1fboY5_723hC7sQMqyz6uGurYqqCG4xFG",
        phone_Number: "6238161701",
        playing_Role: "All-rounder",
        club: "Jokerz",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1iv-n5b0Jy3LnCiRPzEhkKHtwpfBoPQvV",
    },
    {
        timeStamp: "2025/05/20 3:37:55 PM GMT+5:30",
        name: "Mani jockerz ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1viZry3UMaGwSTiMtDVk9MLRqRQsbaypk",
        phone_Number: "7025839343 ",
        playing_Role: "All-rounder",
        club: "Jockerz ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1wbOAljxJQpbDF_QhePRwM7E7RYj1dlcR",
    },
    {
        timeStamp: "2025/05/20 7:11:36 PM GMT+5:30",
        name: "Charly",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1pNBQjAX2tCNf03H4nRSYbB5kvoMQSnuW",
        phone_Number: "7559937279",
        playing_Role: "Batsman",
        club: "Ekr cricketers",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1EOi5mcbxl9HgRnLWCMC5QOIqFIHdoCTq",
    },
    {
        timeStamp: "2025/05/20 7:51:54 PM GMT+5:30",
        name: "Kiran ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1q5l53Q6t9YjEN8If1gWtDicvvCIMQobA",
        phone_Number: "9946250266",
        playing_Role: "Batsman",
        club: "Stallions",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1eZqc6MoSpvD6OoSmU4XSoIZ6Cy3m6Dkw",
    },
    {
        timeStamp: "2025/05/20 8:15:29 PM GMT+5:30",
        name: "Manu",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1olMMt20ptKkCxibwTMPbxebUHcKu9Snd",
        phone_Number: "9072118650",
        playing_Role: "Bowler",
        club: "Jokerz",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1KMtMGoSleQRmbhXMr2A3PvC_H9Uox0jM",
    },
    {
        timeStamp: "2025/05/20 9:11:53 PM GMT+5:30",
        name: "Manju",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1SMpxlvP8epmLfR5Lnndv1zvkrcDu_fpy",
        phone_Number: "7356948017",
        playing_Role: "All-rounder",
        club: "Ekr Cricketers",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1BbyokykSdMdwVDhOgEwXsJ18Oys-hp5V",
    },
    {
        timeStamp: "2025/05/20 9:13:51 PM GMT+5:30",
        name: "Praveen",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1-nGJwIf7FkbKTxSm3kwSLQjsdmWqQnbu",
        phone_Number: "9526650092",
        playing_Role: "Batsman",
        club: "Erumaikkaranoor ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1GRBRJD-uPkEIs2Lvkqim3DAhlHUgdcgk",
    },
    
    {
        timeStamp: "2025/05/21 9:43:11 AM GMT+5:30",
        name: "Salman farish ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1h4csArCu70swysZq_V3UnZi9yA4OWhI8",
        phone_Number: "9074215058",
        playing_Role: "All-rounder",
        club: "Nallur rising star's ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1U_R7cjpzt6RS8T1QY3Pby7t3Np4eom-Z",
    },
    {
        timeStamp: "2025/05/21 9:49:54 AM GMT+5:30",
        name: "ANDROS",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1ZxLXByvdiYVt4fxhqKs9nh0GyPL9Hn3I",
        phone_Number: "9497312928",
        playing_Role: "All-rounder",
        club: "Nallur rising star",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1EPc2B--IqQ4v4ZvS0EKTdNduFOywyQlT",
    },
    {
        timeStamp: "2025/05/21 7:43:52 PM GMT+5:30",
        name: "Akshay",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1g8cYUrbm8P0OZpsoiKDV8dVMw-oh6cXJ",
        phone_Number: "8891163595",
        playing_Role: "All-rounder",
        club: "Bsa",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1DB38g4SzGN9IIZFZ_z9i-TZjoPaY1Uan",
    },
    {
        timeStamp: "2025/05/21 7:51:58 PM GMT+5:30",
        name: "Skuttan",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1x1j5AmS6BzvhEmnQ-d7AyMfVFM7l_nrh",
        phone_Number: "7560969865",
        playing_Role: "All-rounder",
        club: "Bsa",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1GIVmM92j4vTSh29KIQoN1WnCxbMzhZut",
    },
    {
        timeStamp: "2025/05/21 8:04:18 PM GMT+5:30",
        name: "Sruthish s",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1wPuqNnLOp1H1U9D9PV7VSXEJY99fuyfB",
        phone_Number: "8590370524",
        playing_Role: "All-rounder",
        club: "Bsa",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1U1XIdk3pfg7DmSpCSLKPIGBKeZkonx43",
    },
    {
        timeStamp: "2025/05/21 10:16:27 PM GMT+5:30",
        name: "Rajesh",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1_-89xLBzbcCvGaC6eKHeKQ-IRfXgUsTZ",
        phone_Number: "9809690208",
        playing_Role: "All-rounder",
        club: "KL BROTHERS",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1FeMY27_IEe8c6mYzN0IZPPYTFvSFB2pk",
    },
    {
        timeStamp: "2025/05/22 11:15:41 AM GMT+5:30",
        name: "Abbas ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1yMXfqt9A8XI06eESJPKc3Dai1w1Gkaui",
        phone_Number: "9995634599",
        playing_Role: "All-rounder",
        club: "Kl brother ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1p99enwGkFUiYNUaIPX67TDAlnDTaTTn_",
    },
    {
        timeStamp: "2025/05/22 1:11:42 PM GMT+5:30",
        name: "Kalai ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1-5dKHiO20BdYtm8ZYjM6nS34Z1GtGmtd",
        phone_Number: "9562828301",
        playing_Role: "All-rounder",
        club: "Phoenix Kozhinjampara ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1p0EUMalFN5HtWkMdAxrVywA4MK4zh5Hz",
    },
    {
        timeStamp: "2025/05/22 1:17:08 PM GMT+5:30",
        name: "Agilesh ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1LzGbjKlrxXUY54LDxhwGR-bgtFMqYP5J",
        phone_Number: "9809200670",
        playing_Role: "All-rounder",
        club: "Phoenix ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1aBCKGCbxB4Cg8aC-vSQ52Tj8b8CXNP0L",
    },
    {
        timeStamp: "2025/05/22 1:20:40 PM GMT+5:30",
        name: "Anees uv",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1ZxDvabp-EtpqGrlCaD3Pc-OKvcDv5UGf",
        phone_Number: "8137007221",
        playing_Role: "All-rounder",
        club: "Walayar Champions club ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1vx7j_FXXgGv5v91r2iGfsB4GoejSHMCd",
    },
    {
        timeStamp: "2025/05/22 1:24:05 PM GMT+5:30",
        name: "Bibinraj",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1qo2lzKpy87ez-w9JCRDBrWx6TU8wQ5Jv",
        phone_Number: "9946497133",
        playing_Role: "All-rounder",
        club: "Kongampara ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1-fFJ7-G83s851qgAeCOqcB6VIavWUtll",
    },
    {
        timeStamp: "2025/05/22 7:06:01 PM GMT+5:30",
        name: "Asharaf ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1e9lewI8sOcLaDYv6RBhCmADC0qLgdkVC",
        phone_Number: "7708609308",
        playing_Role: "All-rounder",
        club: "Pheonix ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=14Of0ra1YbJ8ze4V9yQKW3dEoPfo-gKZe",
    },
    {
        timeStamp: "2025/05/22 7:19:20 PM GMT+5:30",
        name: "Jose",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1NOTQ_ytadgSWuBZU_sR_0UV28EXRZNwr",
        phone_Number: "9656289774",
        playing_Role: "All-rounder",
        club: "Klcc",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1zlJqnBk4NPOEwVIZQtmY2nX-eECPkh63",
    },
    {
        timeStamp: "2025/05/22 7:20:41 PM GMT+5:30",
        name: "Albi",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1OPCIp_ZFQ1FztmbUcAlVcRYtwLxn67le",
        phone_Number: "7907877289",
        playing_Role: "All-rounder",
        club: "Scorpions ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Dr8G8auDd76uyU4PE50Y96e6D71hBOxf",
    },
    {
        timeStamp: "2025/05/22 7:21:47 PM GMT+5:30",
        name: "Kevin ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=13YZCTNNBMEk3NPyAsaLL6s-SEaWelnSx",
        phone_Number: "9207901704",
        playing_Role: "All-rounder",
        club: "Stallions lo",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1h9YHUhuEREUFknDgZG0dmWSu-OegMovz",
    },
    {
        timeStamp: "2025/05/22 7:24:13 PM GMT+5:30",
        name: "Jerom",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1ONJn6OO-1dxi5cyKKdyowVWkMbJUG6K8",
        phone_Number: "9539680590",
        playing_Role: "All-rounder",
        club: "Blasters cc ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1zrumKzFtvM0E7zZqeUQrwD_LHmKaJk5z",
    },
    {
        timeStamp: "2025/05/22 8:15:23 PM GMT+5:30",
        name: "Staney",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1RpHJQONUkBJKgi2PH2RLNT_id0v577it",
        phone_Number: "9074172452",
        playing_Role: "All-rounder",
        club: "Pkd boys",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1N0dvvbm7cLeqiJh7nCkej8nTE4f_7DoV",
    },
    {
        timeStamp: "2025/05/22 8:17:24 PM GMT+5:30",
        name: "KATHIR",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1bBdvNHYRmcgw1JaKVWSlpnqbH9NBEkoe",
        phone_Number: "8075802086",
        playing_Role: "All-rounder",
        club: "KL.BROTHERS",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1rGpr4NTeBaNL9cpKhCTbZXaWPAPb5L3O",
    },
    {
        timeStamp: "2025/05/22 10:50:35 PM GMT+5:30",
        name: "Aji",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1PHbDgsj6Wkfgzw_ywXN4gG7NkBV5JWic",
        phone_Number: "7012816557",
        playing_Role: "All-rounder",
        club: "New Royals vattappara",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1C9z36gtZg5XEu_5cp0HUJtNl59TgEaov",
    },
    {
        timeStamp: "2025/05/22 10:55:19 PM GMT+5:30",
        name: "Adhi",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=168QA75Trrc75X7sbcpAu4O4iRUAAcxMa",
        phone_Number: "7736055641",
        playing_Role: "All-rounder",
        club: "New Royals vattappara",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=18Bs9QYKolVTci129voO86_UGILisWpfl",
    },
   
    {
        timeStamp: "2025/05/23 8:30:46 AM GMT+5:30",
        name: "STANLY LEO V",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1OpN_VqtCuRqOYmhEjJVdqg8P9oU1yTZ_",
        phone_Number: "8082202877",
        playing_Role: "All-rounder",
        club: "Stallions ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Jp9tFkcxDlcCy1bWkZ70fIAIMWCuTLUg",
    },
    {
        timeStamp: "2025/05/23 8:41:59 AM GMT+5:30",
        name: "Ebin",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=14G6oAdO8WIOhsjRr1lcKgcAuH9jpxRS5",
        phone_Number: "7907978734",
        playing_Role: "Batsman",
        club: "Pkd boys",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1nTjEht3pD9wvtdE2-nzMUIFSwme78bHK",
    },
    {
        timeStamp: "2025/05/23 8:53:13 AM GMT+5:30",
        name: "Nithin ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1Z3TltX6k3_0aqMClcvB9nqP9QZNbU5j5",
        phone_Number: "9995391974",
        playing_Role: "All-rounder",
        club: "PKD BOYS",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Si8IicifIaf1IiGwlkwg55qahzxvQcpk",
    },
    {
        timeStamp: "2025/05/23 9:11:47 AM GMT+5:30",
        name: "Reni",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1UaYOe3jLsG_nz-_aTlYrgZHaYbUk4WHT",
        phone_Number: "8848936996",
        playing_Role: "Batsman",
        club: "Unbeatable titans",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1Mr6YOlEQkYauSU6LkLoMQS808mKMKWH6",
    },
    {
        timeStamp: "2025/05/23 11:30:07 AM GMT+5:30",
        name: "Midhush",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1ZD31jtsDL5YycYicejLrV5HUgESUkqqD",
        phone_Number: "9777104642",
        playing_Role: "Bowler",
        club: "Devilzz",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1tc5BtuD9uGavsLWf3Vaem3OgHxQH0a9N",
    },
    {
        timeStamp: "2025/05/23 1:19:33 PM GMT+5:30",
        name: "Naveen NS",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=19l35wI4qzZyy727Lyb84Rlg_lrAv3081",
        phone_Number: "8848209277",
        playing_Role: "Batsman",
        club: "Phoenix",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=16ZWlKxxNdd96G_PIRI6Y0C_wbWndlKrh",
    },
    {
        timeStamp: "2025/05/23 6:22:18 PM GMT+5:30",
        name: "Dhanee",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1nBMY5X6ONCbgOHcqg3BumPLaZ_HsmHdH",
        phone_Number: "+918590188293",
        playing_Role: "All-rounder",
        club: "Fighters kozhinjamPara ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1v6bzeiBFlIYW_dMPGzK3f68fdlSKWgb4",
    },
    {
        timeStamp: "2025/05/23 6:44:42 PM GMT+5:30",
        name: "Jikson A",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1gxQJi1bYYmwTnEa-IK7tTHUVDvrDZtmt",
        phone_Number: "7012295719",
        playing_Role: "All-rounder",
        club: "Skyhawks ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1G8q_h-6P8cWq5SF741Sg5_LtCTRIvEkv",
    },
    {
        timeStamp: "2025/05/23 8:41:19 PM GMT+5:30",
        name: "Akash",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1d5hwi9cmxqs3PgmOml5wyjh1Hrc-iIev",
        phone_Number: "8078908124",
        playing_Role: "All-rounder",
        club: "Phoenix ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=11jVvHKUpYYiHvN-U1NNZprVrGCoKz3x5",
    },
    {
        timeStamp: "2025/05/23 8:49:31 PM GMT+5:30",
        name: "Rassu",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1hGhhSfTxLcVyfbjZpBwr__KDR1GQkzcP",
        phone_Number: "8547611432",
        playing_Role: "Bowler",
        club: "Phoenix ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1MBzTVxaQyejfZ4veGfJZ6pxbz2GOktHh",
    },
    {
        timeStamp: "2025/05/24 9:35:51 AM GMT+5:30",
        name: "Kalai ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1760hrvfC0k16CWs6lX70KlHJslXctbU8",
        phone_Number: "9562828301",
        playing_Role: "Wicket Keeper",
        club: "Pheonix ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1CzsN2qWKei0lKRkA7J61BXgnlomNY-VP",
    },
    {
        timeStamp: "2025/05/24 2:24:46 PM GMT+5:30",
        name: "Appu",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1BhiKDVXnMb6mIiJSC_h9jsUbvHWrowQt",
        phone_Number: "9074065050",
        playing_Role: "Batsman",
        club: "Chandhapetta",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=15DX-o8ACOxNaJxmNMUsHtIm_KEe1Nkjk",
    },
    {
        timeStamp: "2025/05/24 2:26:36 PM GMT+5:30",
        name: "Abbas",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1_FM04LBIkoyLaHVxwdSRRIet_Hn1Z47_",
        phone_Number: "9495229471",
        playing_Role: "Batsman",
        club: "Chellengers",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1GD7gvD8wW4PcrNB5dVqQ5_jVoC-uM3Yh",
    },
    {
        timeStamp: "2025/05/25 9:10:53 AM GMT+5:30",
        name: "Darry",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=13XvSHEN4_QJGmbWQDbqWZmaBnzvtXcHR",
        phone_Number: "7994919834",
        playing_Role: "All-rounder",
        club: "Pkd boys",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1QiMvEKgo8k5q0BNYM2WIwfYBh7Hmkk4-",
    },
    {
        timeStamp: "2025/05/25 9:16:37 AM GMT+5:30",
        name: "Jekan",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1GJiw7TylEV4ex7FpuTX7zGr9hJHFkbyt",
        phone_Number: "8848861653",
        playing_Role: "All-rounder",
        club: "Pkd boys",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1KJxsKmjhFl2zr_jgzwwYatodPNvcl-6R",
    },
    {
        timeStamp: "2025/05/25 12:24:22 PM GMT+5:30",
        name: "Lara ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=14fjlWOJ6rjf2o1Vqg505JrbT_NgBMAKH",
        phone_Number: "8921188744",
        playing_Role: "Batsman",
        club: "Nil",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1M_HGY-yfWydI-qJ6-aNdMmKLUAOjfmKc",
    },
    {
        timeStamp: "2025/05/25 12:35:38 PM GMT+5:30",
        name: "JENIFER ANTONY",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=14rZYGiNk6S_NNmUHmySZC5iRGC0BXxDl",
        phone_Number: "9645257801",
        playing_Role: "All-rounder",
        club: "Stephen CC",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1AKdhGCers8W69cPhGWxDygxIuWjby47T",
    },
    {
        timeStamp: "2025/05/25 1:13:03 PM GMT+5:30",
        name: "Akhil",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1pX5fsw1BVa-HqBFcTHGh29dznzSxgVmL",
        phone_Number: "7306177117",
        playing_Role: "All-rounder",
        club: "Gmsc",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1FVvAtNCLX4msxQdn_3bV0nKqU_1CBgvL",
    },
    {
        timeStamp: "2025/05/25 1:55:59 PM GMT+5:30",
        name: "Adhul",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=15K1oGK0hosWrjbNAgx7PsM3sBrEWbmir",
        phone_Number: "6238331003",
        playing_Role: "All-rounder",
        club: "Shine ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1PcrIEMb59rVB5yUn7W5Kw1fVJO3Pbe-O",
    },
    {
        timeStamp: "2025/05/25 2:21:18 PM GMT+5:30",
        name: "TINGU",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1XB_gDm8B3HrfbzIhw37Kw_DJGEjXfXmu",
        phone_Number: "8943711379",
        playing_Role: "All-rounder",
        club: "Phoenix",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1FhYY5VCCsGMg-JsTvUgMZyO50eQEzLKh",
    },
    {
        timeStamp: "2025/05/25 2:21:49 PM GMT+5:30",
        name: "Babu",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1qV95ajwbeLuHolssYpxuFz9tnzXXKwjm",
        phone_Number: "7907191682",
        playing_Role: "Bowler",
        club: "King cobra ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1vl-2IDvSAA_-I4ZBm2e2Q6bu79NppRlD",
    },
    {
        timeStamp: "2025/05/25 2:23:54 PM GMT+5:30",
        name: "Athul",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1PuCF5NMdkQ2KG5sgpyboSPHkU8e5zRP_",
        phone_Number: "8089677002",
        playing_Role: "Batsman",
        club: "Chellengers ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1xWzuZTUHFvY6yuFaY3BG6w1hrXf4LwYO",
    },
    {
        timeStamp: "2025/05/25 2:24:59 PM GMT+5:30",
        name: "Unni",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1as96xi35rA5RDA6VMvGCY39ZneKKrZUA",
        phone_Number: "9074812040",
        playing_Role: "Bowler",
        club: "Chellengers ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1m-CAUYdHfTy8nCj1W4AKPyrMdlkXMOJI",
    },
    {
        timeStamp: "2025/05/25 2:39:31 PM GMT+5:30",
        name: "Rahul",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1AwpkeLbpmc3bd8tGOrzPpKDo8J2tKsiP",
        phone_Number: "9995671287",
        playing_Role: "All-rounder",
        club: "Sorappara",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=17Pu77wDDJ6zsdCE9qLJM9gvWkGXFPIa2",
    },
    {
        timeStamp: "2025/05/25 2:42:15 PM GMT+5:30",
        name: "Johnson",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1v284O1IO98AE_OHt6lpMVHYf_GiQDX6c",
        phone_Number: "9037277961",
        playing_Role: "Batsman",
        club: "Ekr cricketers ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1idhJ682kjPhIzuD6-So57kcuH2appg7L",
    },
    {
        timeStamp: "2025/05/25 2:43:44 PM GMT+5:30",
        name: "Aswin ",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1fDJRukv3U5fPbyWrHVMwURtEepK6xJdD",
        phone_Number: "9895854794",
        playing_Role: "Bowler",
        club: "STALLIONS",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1tZSbXeJcFQYsj46yArpcPBP9B5jxET-z",
    },
    {
        timeStamp: "2025/05/25 2:45:18 PM GMT+5:30",
        name: "Devit",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1PllSfjbnLBRDqVoUxxsGamcx6yO7pbSf",
        phone_Number: "7736198405",
        playing_Role: "All-rounder",
        club: "Ekr cricketers ",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1vtFhUzO7CAlgsQWlnzQ_RCT_sX2_kkym",
    },
    {
        timeStamp: "2025/05/25 2:47:43 PM GMT+5:30",
        name: "Akash",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1Ah-IQovlJY8KdKCfrFEANSugjR_M7urW",
        phone_Number: "9809736361",
        playing_Role: "All-rounder",
        club: "Parisakkal",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1B7F0rM4F9CNczCVC-RF8c--actWQIWWc",
    },
    {
        timeStamp: "2025/05/25 2:49:18 PM GMT+5:30",
        name: "Viji",
        photo: "https://drive.google.com/u/2/open?usp=forms_web&id=1BplKP6AJjeKXZ7mfoJPZjuAZJBGM0aZU",
        phone_Number: "7994852078",
        playing_Role: "All-rounder",
        club: "Stallions",
       upload_Screen_Shot_of_payment: "https://drive.google.com/u/2/open?usp=forms_web&id=1g58VTWNJEe0YwO_t-iazQA70RHTk0ZyN",
    }
]

export default players;